import { User } from 'src/interfaces/User';

export const USERS: User[] = [
  {
    firstName: 'Brenden',
    lastName: 'Wagner',
    country: 'United States of America, California',
    nationality: 'American',
    company: 'Facebook',
    designation: 'Software Engineer',
    workExp: 8,
    cv: '',
    dataSource: 'Facebook',
  },
  {
    firstName: 'Cara',
    lastName: 'Stevens',
    country: 'United States of America, New york',
    nationality: 'American',
    company: 'Walmart',
    designation: 'Sales Assistant',
    workExp: 5,
    cv: '',
    dataSource: 'Google',
  },
  {
    firstName: 'Cedric',
    lastName: 'Kelly',
    country: 'Scotland, Glasgow City',
    nationality: 'Scottish',
    company: 'Data Tech',
    designation: 'Senior Javascript Developer',
    workExp: 7,
    cv: '',
    dataSource: 'Monster Gulf',
  },
  {
    firstName: 'Doris',
    lastName: 'Wilder',
    country: 'Australia, Queensland',
    nationality: 'Australian',
    company: 'Telstra',
    designation: 'Support Engineer',
    workExp: 3,
    cv: '',
    dataSource: 'JobsDB',
  },
  {
    firstName: 'Jenny',
    lastName: 'Chang',
    country: 'Singapore, Singapore',
    nationality: 'Chinese',
    company: 'Singapore Airlines',
    designation: 'Regional Director',
    workExp: 15,
    cv: '',
    dataSource: 'Twitter',
  },
];
